-- CREATE TABLE FOO (ID VARCHAR(64), BAR VARCHAR(64));
-- CREATE TABLE FOO (ID VARCHAR(64), BAR VARCHAR(64), IS_DELETE INT(1));
-- CREATE TABLE FOO (ID VARCHAR(64), BAR VARCHAR(64), IS_DELETE INT(1), CREATE_DATE DATE);
CREATE TABLE FOO (ID VARCHAR(64), BAR VARCHAR(64), IS_DELETE INT(1), CREATE_DATE DATE
, MONEY DECIMAL, AGE BIGINT);